### ISSUE TITLE
Sandstorm webpage: “This recording has been archived”

### ISSUE THREAD

**Issue by LemmingAvalanche** [sandstorm-io/sandstorm-website#316] opened 2020-02-04 12:08 UTC
https://sandstorm.io/install :

![image](https://user-images.githubusercontent.com/2229597/73743589-36775480-474f-11ea-9699-ea24a5520022.png)

**Comment by ocdtrekkie** [comment] 2020-02-04 12:45
This is a duplicate of #309, and a PR to fix it, #307, is already open.

Little bit of web bitrot, sorry about that! Thanks for reporting it though.

**Closed by ocdtrekkie** 2020-02-04 12:45 UTC
